// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6oIxcXrjXc49h0I0RKgDBQD6V6208VNU',
    appId: '1:933953660440:web:4e0a516824b37c1c38456d',
    messagingSenderId: '933953660440',
    projectId: 'noteapp-fea58',
    authDomain: 'noteapp-fea58.firebaseapp.com',
    storageBucket: 'noteapp-fea58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByFCRf4nKWiLpcstBKr2DumbAHzP2_AdY',
    appId: '1:933953660440:android:2e13d7c08b08c05138456d',
    messagingSenderId: '933953660440',
    projectId: 'noteapp-fea58',
    storageBucket: 'noteapp-fea58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGF1hi5mwNJ0AoClh-JvgxWaLS9SwqARg',
    appId: '1:933953660440:ios:d20e482a6bd963d638456d',
    messagingSenderId: '933953660440',
    projectId: 'noteapp-fea58',
    storageBucket: 'noteapp-fea58.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );
}
